# This workflow is used to deploy the Firebase Functions to Firebase.
# It is triggered when a push is made to the main branch.
# It uses the Google GitHub Actions to authenticate with Firebase.
# It then uses the Firebase Tools to deploy the functions.
# Ref: https://firebase.google.com/docs/functions/deploy-github-ci  

name: Deploy to Firebase Functions

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NODE_ENV: production
      API_ENDPOINT: ${{ secrets.API_ENDPOINT_PRODUCTION }}
      MAX_RETRIES: 3
      TIMEOUT_SECONDS: 60
      MEMORY: 256MiB
      MAX_INSTANCES: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 'Create .env file'
        env:
          SOCIAL_MEDIA_POST_API_URL: ${{ secrets.SOCIAL_MEDIA_POST_API_URL }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PLATFORM_ACCESS_TOKEN }}
          INSTAGRAM_PAGE_ID: ${{ secrets.INSTAGRAM_PAGE_ID }}
          INSTAGRAM_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PLATFORM_ACCESS_TOKEN }}
          THREADS_USER_ID: ${{ secrets.THREADS_USER_ID }}
          CONFIG_JSON: ${{ secrets.FIREBASE_CONFIG_PRODUCTION }}
        run: |
          echo "SOCIAL_MEDIA_POST_API_URL=${{ env.SOCIAL_MEDIA_POST_API_URL }}" >> .env
          echo "FACEBOOK_PAGE_ID=${{ env.FACEBOOK_PAGE_ID }}" >> .env
          echo "FACEBOOK_PAGE_ACCESS_TOKEN=${{ env.FACEBOOK_PAGE_ACCESS_TOKEN }}" >> .env
          echo "INSTAGRAM_PAGE_ID=${{ env.INSTAGRAM_PAGE_ID }}" >> .env
          echo "INSTAGRAM_PAGE_ACCESS_TOKEN=${{ env.INSTAGRAM_PAGE_ACCESS_TOKEN }}" >> .env
          echo "THREADS_USER_ID=${{ env.THREADS_USER_ID }}" >> .env
          echo "CONFIG_JSON=${{ env.CONFIG_JSON }}" >> .env
          cat .env

      - name: Install dependencies
        run: cd functions && npm ci

      - name: Build functions
        run: cd functions && npm run build

      - name: Install Firebase Tools
        run: cd functions && npm install -g firebase-tools

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CI_DEPLOY }}'

      - name: Deploy to Production
        run: npm run deploy 